=== FlorisdeWaal/Plantismash_dev/antismash/generic_modules/active_site_finder/config/SignatureResources.dtd
<!-- Definition for antiSMASH SignatureResources.xml -->

<!-- resource is the root element in the XML file; there is only 1 resource -->
<!ELEMENT resource ( analysis+ ) >
<!ATTLIST resource xmlns:xsd CDATA #REQUIRED >
<!ATTLIST resource xmlns:xsi CDATA #REQUIRED >


<!ELEMENT analysis ( Prerequisite, Execute, Alignment, description, referenceList ) >
<!-- each implemented analysis is organised in an analysis element, which has sub-elements:
Prerequisites: defines the sequence features that the analysis can be applied for,
Execute: Parameters for external program execution
Alignment: Defintion of positions to look at
description: Short description of the analysis
referenceList: References describing the analysis

each analysis needs the attributes "name" and "type" defined

-->
<!ATTLIST analysis name ( #CDATA ) #REQUIRED >
<!ATTLIST analysis type ( #CDATA ) #REQUIRED >


<!ELEMENT Prerequisite ( primary_tag_type, tag, tag_value ) >
<!-- The prerequisite element defines the feature in the seq_record that are subjected to the analysis:
primary_tag_type: e.g. PFAM_domain
tag: e.g. domain
tag_value: e.g. PKS_AT

XML example:
<Execute program="hmmpfam2" CaptureConsole="TRUE">
			<parameters>
				<parameter name='score' prefix="-T">0</parameter>
				<parameter name='evalue' prefix="-E">0.1</parameter>
				<parameter name='cpus' prefix="--cpu">1</parameter>
			</parameters>
			<database>PKSI-AT.hmm2</database>
			<db_source>CLUSEAN</db_source>
			<BioPythonParser>hmmer2-text</BioPythonParser>
		</Execute>
-->
<!ELEMENT primary_tag_type ( #PCDATA ) >
<!ELEMENT tag ( #PCDATA ) >
<!ELEMENT tag_value ( #PCDATA ) >


<!ELEMENT Execute ( BioPythonParser | database | db_source | parameters )* >
<!-- The Execute element defines the external program execution paramteres
For example see Prerequisite element description-->

<!ATTLIST Execute CaptureConsole ( #CDATA ) NMTOKEN #IMPLIED>
<!ATTLIST Execute program ( #CDATA ) #REQUIRED >
<!ATTLIST Execute UseSTDIN ( #CDATA ) #IMPLIED >
<!ATTLIST Execute STDINprefix ( #CDATA ) #IMPLIED >

<!ELEMENT parameters ( parameter+ ) >

<!ELEMENT parameter ( #PCDATA ) >
<!ATTLIST parameter name ( #PCDATA ) #IMPLIED >
<!ATTLIST parameter prefix ( #PCDATA) #IMPLIED >

<!ELEMENT database ( #PCDATA ) >
<!ELEMENT db_source ( #PCDATA ) >
<!ELEMENT BioPythonParser ( #PCDATA ) >



<!ELEMENT Alignment ( scaffold, choice* ) >
<!-- The alignment element defines the aa positions (relative to the hmm hit) that are extracted

scaffold: These are "non active site" residues that are conserved and can be used to validate tha alignment
choice: choice elements are finally evaluated and their "result" attribute is annotated if there is a match

Example:
		<Alignment>
			<scaffold>
				<scaffoldOffset>93,94,95,120,196,198,199,227,244,245</scaffoldOffset>
				<scaffoldValue>G,H,S,R,A,H,S,S,Y,W</scaffoldValue>
			</scaffold>
			<choice result="Malonyl-CoA specific">
				<offset>195,197</offset>
				<value>H,F</value>
				<comment>AT domain specific for malonyl-CoA</comment>
			</choice>
			<choice result="Methylmalonyl-CoA specific">
				<offset>195,197</offset>
				<value>Y,S</value>
				<comment>AT domain specific for methylmalonyl-CoA</comment>
			</choice>
		</Alignment>

-->

<!ELEMENT scaffold ( scaffoldOffset, scaffoldValue, scaffoldEmission? ) >
<!-- Definition of the scafold positions; mutlitple values are sparated by ","
scaffold Emission: List of HMM emission values (from reference alignment tested against the HMM) optional
scaffoldOffset: List of offsets
scaffoldValues: amino acids at these positions
-->
<!ELEMENT scaffoldEmission ( #PCDATA ) >
<!ELEMENT scaffoldOffset ( #PCDATA ) >
<!ELEMENT scaffoldValue ( #PCDATA ) >

<!ELEMENT choice ( comment | offset | value | valueEmission )* >
<!-- Definition of the choice element, analogous to scaffold; with additional comment element -->
<!ATTLIST choice result CDATA #REQUIRED >
<!ELEMENT offset ( #PCDATA ) >
<!ELEMENT value ( #PCDATA ) >
<!ELEMENT valueEmission ( #PCDATA ) >

<!ELEMENT comment ( #PCDATA ) >

<!ELEMENT description ( #PCDATA ) >
<!-- General description of the analysis -->

<!ELEMENT referenceList ( reference ) >
<!-- List of references -->
<!ELEMENT reference ( #PCDATA ) >

=== FlorisdeWaal/Plantismash_dev/antismash/generic_modules/active_site_finder/config/SignatureResources.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE resource SYSTEM "SignatureResources.dtd">

<resource xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<analysis name="PKSI_KR_Stereo" type="prediction">
		<Prerequisite>
			<primary_tag_type>aSDomain</primary_tag_type>
			<tag>domain</tag>
			<tag_value>PKS_KR</tag_value>
		</Prerequisite>
		<Execute program="hmmpfam2" CaptureConsole="True" UseSTDIN="True" STDINprefix="-">
			<!-- Currently, the location of the hmmpfam2 binary and the database location 
				is inferred from the antismash configuration file! -->

			<parameters>
				<!-- If prefixes for parameters are required they can be added as attribute 
					prefix -->
				<parameter name='score' prefix="-T">0</parameter>
				<parameter name='evalue' prefix="-E">0.1</parameter>
				<parameter name='cpus' prefix="--cpu">1</parameter>
			</parameters>
			<database>PKSI-KR.hmm2</database>
			<BioPythonParser>hmmer2-text</BioPythonParser>
			<db_source>CLUSEAN</db_source>
		</Execute>
		<Alignment>
			<scaffold>
				<scaffoldOffset>149, 162, 166</scaffoldOffset>
				<scaffoldValue>S,Y,N</scaffoldValue>
			</scaffold>
			<choice result="KR catalyzing D-configuration product">
				<offset>102</offset>
				<value>D</value>
				<comment>KR domain putatively catalyzing D-configuration product formation</comment>
			</choice>
			<choice result="KR catalyzing L-configuration product">
				<offset>102</offset>
				<value>[^D]</value>
				<comment>KR domain putatively catalyzing L-configuration product formation</comment>
			</choice>
		</Alignment>
		<description>Pediction of PKSI KR specificities according to Reid et al., Biochemistry 2003, 42, 72-79</description>
		<referenceList>
			<reference>Reid, R., M. Piagentini, E. Rodriguez, G. Ashley, N., Viswanathan, J. Carney, D. V. Santi, C. R. Hutchinson, and R. McDaniel. 2003. A model of structure and catalysis for ketoreductase domains in modular polyketide synthases. Biochemistry 42:72-79.</reference>
		</referenceList>
	</analysis>
	<analysis name="ASP_KS" type="active_site_toCorrect">
		<Prerequisite>
			<primary_tag_type>aSDomain</primary_tag_type>
			<tag>domain</tag>
			<tag_value>PKS_KS</tag_value>
		</Prerequisite>
		<Execute program="hmmpfam2" CaptureConsole="True" UseSTDIN="True" STDINprefix="-"> program="hmmpfam2" CaptureConsole="True" UseSTDIN="True">
			<!-- Currently, the location of the hmmpfam2 binary and the database location 
				is inferred from the antismash configuration file! -->

			<parameters>
				<!-- If prefixes for parameters are required they can be added as attribute 
					prefix -->
				<parameter name='score' prefix="-T">0</parameter>
				<parameter name='evalue' prefix="-E">0.1</parameter>
				<parameter name='cpus' prefix="--cpu">1</parameter>
			</parameters>
			<database>PKSI-KS_N.hmm2</database>
			<db_source>PFAM</db_source>
			<BioPythonParser>hmmer2-text</BioPythonParser>
		</Execute>
		<Alignment>
			<scaffold>
				<scaffoldOffset>176,186,187,188</scaffoldOffset>
				<scaffoldValue>G,S,S,S</scaffoldValue>
				<scaffoldEmission>0.99,0.9,0.81,0.81</scaffoldEmission>
			</scaffold>
			<choice result="active site cysteine found">
				<offset>185</offset>
				<value>C</value>
				<valueEmission>0.98</valueEmission>
				<comment>Active site cysteine</comment>
			</choice>
		</Alignment>
		<description>KS active site cysteine according to Huang et al
			Microbiology 147 (2001), 631-642</description>
		<referenceList>
			<reference>Guozhong Huang, Lianhui Zhang and Robert G. Birch, A multifunctional polyketide–peptide synthetase essential for albicidin biosynthesis in Xanthomonas albilineans, Microbiology 147 (2001), 631-642</reference>
		</referenceList>
	</analysis>
	
	<analysis name="ASP_KS_C" type="active_site_toCorrect">
		<Prerequisite>
			<primary_tag_type>aSDomain</primary_tag_type>
			<tag>domain</tag>
			<tag_value>PKS_KS</tag_value>
		</Prerequisite>
		<Execute program="hmmpfam2" CaptureConsole="True" UseSTDIN="True" STDINprefix="-">
			<!-- Currently, the location of the hmmpfam2 binary and the database location 
				is inferred from the antismash configuration file! -->

			<parameters>
				<!-- If prefixes for parameters are required they can be added as attribute 
					prefix -->
				<parameter name='score' prefix="-T">0</parameter>
				<parameter name='evalue' prefix="-E">0.1</parameter>
				<parameter name='cpus' prefix="--cpu">1</parameter>
			</parameters>
			<database>PKSI-KS_C.hmm2</database>
			<db_source>PFAM</db_source>
			<BioPythonParser>hmmer2-text</BioPythonParser>
		</Execute>
		<Alignment>
			<scaffold>
				<scaffoldOffset>47,50,51,52,53,56,57,60,106,110,117,123</scaffoldOffset>
				<scaffoldValue>E,G,T,G,T,G,D,E,K,G,G,K</scaffoldValue>
				<scaffoldEmission>0.96,0.92,0.95,0.94,0.95,0.96,0.99,0.99,1,0.99,0.96,0.93</scaffoldEmission>
			</scaffold>
			<choice result="Active site histidines found">
				<offset>49,111</offset>
				<value>H,H</value>
				<valueEmission>0.95,1</valueEmission>
				<comment>Active site his</comment>
			</choice>
		</Alignment>
		<description>KS active site Histidine according to Huang et al
			Microbiology 147 (2001), 631-642</description>
		<referenceList>
			<reference>Guozhong Huang, Lianhui Zhang and Robert G. Birch, A multifunctional polyketide–peptide synthetase essential for albicidin biosynthesis in Xanthomonas albilineans, Microbiology 147 (2001), 631-642</reference>
		</referenceList>
	</analysis>
	
	<analysis name="ASP_AT" type="active_site">
		<Prerequisite>
			<primary_tag_type>aSDomain</primary_tag_type>
			<tag>domain</tag>
			<tag_value>PKS_AT</tag_value>
		</Prerequisite>
		<Execute program="hmmpfam2" CaptureConsole="True" UseSTDIN="True" STDINprefix="-">
			<!-- Currently, the location of the hmmpfam2 binary and the database location 
				is inferred from the antismash configuration file! -->

			<parameters>
				<!-- If prefixes for parameters are required they can be added as attribute 
					prefix -->
				<!-- If prefixes for parameters are required they can be added as attribute 
					prefix -->
				<parameter name='score' prefix="-T">0</parameter>
				<parameter name='evalue' prefix="-E">0.1</parameter>
				<parameter name='cpus' prefix="--cpu">1</parameter>
			</parameters>

			<database>PKSI-AT.hmm2</database>
			<db_source>CLUSEAN</db_source>
			<BioPythonParser>hmmer2-text</BioPythonParser>
		</Execute>
		<Alignment>
			<scaffold>
				<scaffoldOffset>93,94,97,98</scaffoldOffset>
				<scaffoldValue>G,H,G,E</scaffoldValue>
				<scaffoldEmission>1,1,1,0.94</scaffoldEmission>
			</scaffold>
			<choice result="active site serine found">
				<offset>95</offset>
				<value>S</value>
				<valueEmission>1</valueEmission>
				<comment>Active site serine</comment>
			</choice>
		</Alignment>
		<description>citation missing</description>
		<referenceList>
			<reference>citation missing</reference>
		</referenceList>
	</analysis>
	<analysis name="ACP-type" type="prediction">
		<Prerequisite>
			<primary_tag_type>aSDomain</primary_tag_type>
			<tag>domain</tag>
			<tag_value>ACP</tag_value>
		</Prerequisite>
		<Execute program="hmmpfam2" CaptureConsole="True" UseSTDIN="True" STDINprefix="-">
			<!-- Currently, the location of the hmmpfam2 binary and the database location 
				is inferred from the antismash configuration file! -->

			<parameters>
				<!-- If prefixes for parameters are required they can be added as attribute 
					prefix -->
				<parameter name='score' prefix="-T">0</parameter>
				<parameter name='evalue' prefix="-E">0.1</parameter>
				<parameter name='cpus' prefix="--cpu">1</parameter>
			</parameters>
			<database>PKSI-ACP.hmm2</database>
			<db_source>CLUSEAN</db_source>
			<BioPythonParser>hmmer2-text</BioPythonParser>
		</Execute>
		<Alignment>
			<scaffold>
				<scaffoldOffset>28,30,31</scaffoldOffset>
				<scaffoldValue>G,D,S</scaffoldValue>
				<scaffoldEmission>0.97,0.9,0.98</scaffoldEmission>
			</scaffold>
			<choice result="non-beta-branching ACP">
				<offset>37</offset>
				<value>[^W]</value>
				<valueEmission>0.99</valueEmission>
				<comment>Trp characteristic for beta-branching ACPs found</comment>
			</choice>
			<choice result="beta-branching ACP">
				<offset>37</offset>
				<value>W</value>
				<valueEmission>5.68E-5</valueEmission>
				<comment>Trp characteristic for beta-branching ACPs found</comment>
			</choice>
		</Alignment>
		<description>Beta-branching motif of ACPs according to Haines et al., Nature Chemical Biology 9:685-692 </description>
		<referenceList>
			<reference>Haines et al., A conserved motif flags acyl carrier proteins for beta-branching in polyketide synthesis, Nature Chemical Biology 9:685-692</reference>
		</referenceList>
	</analysis>
	<analysis name="ASP_ACP" type="active_site">
		<Prerequisite>
			<primary_tag_type>aSDomain</primary_tag_type>
			<tag>domain</tag>
			<tag_value>ACP</tag_value>
		</Prerequisite>
		<Execute program="hmmpfam2" CaptureConsole="True" UseSTDIN="True" STDINprefix="-">
			<!-- Currently, the location of the hmmpfam2 binary and the database location 
				is inferred from the antismash configuration file! -->

			<parameters>
				<!-- If prefixes for parameters are required they can be added as attribute 
					prefix -->
				<parameter name='score' prefix="-T">0</parameter>
				<parameter name='evalue' prefix="-E">0.1</parameter>
				<parameter name='cpus' prefix="--cpu">1</parameter>
			</parameters>
			<database>PKSI-ACP.hmm2</database>
			<db_source>CLUSEAN</db_source>
			<BioPythonParser>hmmer2-text</BioPythonParser>
		</Execute>
		<Alignment>
			<scaffold>
				<scaffoldOffset>28,30</scaffoldOffset>
				<scaffoldValue>G,D</scaffoldValue>
				<scaffoldEmission>0.97,0.9</scaffoldEmission>
			</scaffold>
			<choice result="active site serine found">
				<offset>31</offset>
				<value>S</value>
				<valueEmission>0.98</valueEmission>
				<comment>Active site serine</comment>
			</choice>
		</Alignment>
